gitlab-ci: Check for distro version during release build

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -175,6 +175,19 @@ release-verify-fixed-refspecs:
         || { echo \"Error. Non-fixed refspec detected in repo \${KAS_REPO_NAME}. Please set to a git commit hash or tag for a release build\"; exit 1; }; fi
       """
 
+# Ensures that the release selfidentifies correctly
+release-verify-distro-version:
+  rules:
+    - !reference [.release_template, rules]
+  stage: yocto-setup
+  script:
+    - export $(kas shell -c "bitbake -e | grep IRMA6_DISTRO_VERSION | tail -n 1" ${MAIN_KAS_FILES})
+    - >
+      if test "${IRMA6_DISTRO_VERSION}" != "${CI_COMMIT_TAG}"; then
+        echo "Error. IRMA6_DISTRO_VERSION \"${IRMA6_DISTRO_VERSION}\" defined in the kas config does not match the current git tag \"${CI_COMMIT_TAG}\"."
+        exit 1
+      fi
+
 # Ensures that the release sstate cache is empty before any build is started.
 # This ensures the release is built from scratch (build reproducibility).
 release-wipe-release-sstate-cache:
