disable release-verify-fixed-refspecs

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -354,19 +354,19 @@ download-mirror-maintenance:
 
 # Ensures that fixed refspecs are set for all meta-layers.
 # This is vital for build reproducibility.
-release-verify-fixed-refspecs:
-  rules:
-    - !reference [.release_template, rules]
-  stage: release-sanity-checks
-  script:
-    - echo "Ensuring that fixed refspecs are set on meta layers..."
-    - >
-      kas for-all-repos --update ${MAIN_KAS_FILES} """
-      if [ \"\${KAS_REPO_NAME}\" != \"this\" ]; then
-        git checkout \${KAS_REPO_REFSPEC} \
-        && git rev-parse --abbrev-ref HEAD | grep -qE \"^HEAD\\s*$\" \
-        || { echo \"Error. Non-fixed refspec detected in repo \${KAS_REPO_NAME}. Please set to a git commit hash or tag for a release build\"; exit 1; }; fi
-      """
+# release-verify-fixed-refspecs:
+#   rules:
+#     - !reference [.release_template, rules]
+#   stage: release-sanity-checks
+#   script:
+#     - echo "Ensuring that fixed refspecs are set on meta layers..."
+#     - >
+#       kas for-all-repos --update ${MAIN_KAS_FILES} """
+#       if [ \"\${KAS_REPO_NAME}\" != \"this\" ]; then
+#         git checkout \${KAS_REPO_REFSPEC} \
+#         && git rev-parse --abbrev-ref HEAD | grep -qE \"^HEAD\\s*$\" \
+#         || { echo \"Error. Non-fixed refspec detected in repo \${KAS_REPO_NAME}. Please set to a git commit hash or tag for a release build\"; exit 1; }; fi
+#       """
 
 # Ensures that the DISTRO_VERSION variable is set correctly
 # release-verify-distro-version:
