tmp test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -105,6 +105,7 @@ todocheck:
   stage: setup
   rules:
     - !reference [.develop_template, rules]
+    - !reference [.release_template, rules]
   image: $TODOCHECK_IMAGE
   tags:
     - gp
@@ -162,12 +163,12 @@ release-verify-distro-version:
   variables:
     MAIN_KAS_FILES: "kas-irma6-base-deploy.yml:kas-irma6-pa.yml"
   script:
-    - export $(kas shell -c "bitbake -e | grep IRMA6_DISTRO_VERSION | tail -n 1" ${MAIN_KAS_FILES})
-    - >
-      if test "${IRMA6_DISTRO_VERSION}" != "2.1.0"; then
-        echo "Error. IRMA6_DISTRO_VERSION \"${IRMA6_DISTRO_VERSION}\" defined in the kas config does not match the current git tag \"2.1.0\"."
-        exit 1
-      fi
+    - kas shell -c "bitbake -e | grep IRMA6_DISTRO_VERSION | tail -n 1" ${MAIN_KAS_FILES}
+      #- >
+      #  if test "${IRMA6_DISTRO_VERSION}" != "2.1.0"; then
+      #    echo "Error. IRMA6_DISTRO_VERSION \"${IRMA6_DISTRO_VERSION}\" defined in the kas config does not match the current git tag \"2.1.0\"."
+      #    exit 1
+      #  fi
 
 # Ensures that the release sstate cache is empty before any build is started.
 # This ensures the release is built from scratch (build reproducibility).
