tmp

diff --git a/buildspecs/build_firmware_images_develop.yml b/buildspecs/build_firmware_images_develop.yml
--- a/buildspecs/build_firmware_images_develop.yml
+++ b/buildspecs/build_firmware_images_develop.yml
@@ -23,15 +23,13 @@ phases:
               #export FOSSOLOGY=":include/kas-irma6-jenkins-fossology.yml"
             #fi
           fi
-      # fossology scan
-      - kas shell -c "export TOKEN=${TOKEN}; export BB_ENV_EXTRAWHITE=\"${BB_ENV_EXTRAWHITE}\"; bitbake mc:${MULTI_CONF}:irma6-deploy -c do_spdx" kas-irma6-pa.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES}:include/kas-irma6-jenkins-fossology.yml
       # clone layer repos & set config files
       #- kas checkout --update kas-irma6-pa.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES}
-      - kas checkout --update kas-irma6-pa.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES}
+      - kas checkout --update kas-irma6-pa.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES}:include/kas-irma6-jenkins-fossology.yml
       # try to checkout the current feature/bugfix/... branch in all iris meta layers
       - >
           if [ "$(basename ${GIT_BRANCH})" != "develop" ] && [ "$(basename ${GIT_BRANCH})" != "master" ] && $(echo "${GIT_BRANCH}" | grep -vqE '^release/.*'); then
-            kas for-all-repos kas-irma6-pa.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES} "if echo \${KAS_REPO_NAME} | grep -qE '.*iris.*'; then echo \"Info: Trying to checkout ${GIT_BRANCH} in \${KAS_REPO_NAME}\"; git checkout ${GIT_BRANCH} 2>/dev/null && echo \"Info: Branch ${GIT_BRANCH} has been checked out in \${KAS_REPO_NAME}\" || echo \"Info: Branch ${GIT_BRANCH} not found in \${KAS_REPO_NAME}\"; fi";
+            kas for-all-repos kas-irma6-pa.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES}:include/kas-irma6-jenkins-fossology.yml "if echo \${KAS_REPO_NAME} | grep -qE '.*iris.*'; then echo \"Info: Trying to checkout ${GIT_BRANCH} in \${KAS_REPO_NAME}\"; git checkout ${GIT_BRANCH} 2>/dev/null && echo \"Info: Branch ${GIT_BRANCH} has been checked out in \${KAS_REPO_NAME}\" || echo \"Info: Branch ${GIT_BRANCH} not found in \${KAS_REPO_NAME}\"; fi";
           fi
   build:
     on-failure: ABORT
@@ -41,7 +39,7 @@ phases:
       # build SDK
       - >
         if [ -n "${SDK_IMAGE}" ]; then
-          kas shell -k -c "bitbake mc:${MULTI_CONF}:${SDK_IMAGE} -c populate_sdk" kas-irma6-pa.yml:include/kas-irma6-${MULTI_CONF}.yml:include/kas-irma6-jenkins-develop.yml${POPULATE_CACHES}
+          kas shell -k -c "bitbake mc:${MULTI_CONF}:${SDK_IMAGE} -c populate_sdk" kas-irma6-pa.yml
         fi
 
   post_build:
