wip

diff --git a/.gitlab/common-template.yml b/.gitlab/common-template.yml
--- a/.gitlab/common-template.yml
+++ b/.gitlab/common-template.yml
@@ -34,13 +34,24 @@
       - tar -I "gzip --best" --exclude=${ARTIFACT_NAME}.tar.gz -cf ${ARTIFACT_NAME}.tar.gz ${ARTIFACT_FOLDER}
       - echo "${ARTIFACT_NAME}.tar.gz is $(echo -n $(ls -lh ${ARTIFACT_NAME}.tar.gz | awk '{print $5}')) in size."
 
+    identify_release_from_multiconf:
+      - >
+        if test "${MULTI_CONF}" = "sc573-gen6" || test "${MULTI_CONF}" = "qemux86-64-r1"; then
+          export RELEASE_NAME="IRMA6"
+          export RELEASE_VERSION="r1"
+        elif test "${MULTI_CONF}" = "imx8mp-irma6r2" || test "${MULTI_CONF}" = "qemux86-64-r2"; then
+          export RELEASE_NAME="IRMA6"
+          export RELEASE_VERSION="r2"
+        else
+          echo "Error: Could not identify release from multi_conf ${MULTI_CONF}"
+          exit 1
+        fi
+
   after_script:
     create-kas-artifact-folder:
-      - mkdir ${KAS_ARTIFACT_FOLDER}
-      - mv ${KAS_TMPDIR}/deploy ${KAS_ARTIFACT_FOLDER}
-      - mv ${BUILDDIR}/buildhistory ${KAS_ARTIFACT_FOLDER}
+      - make create-kas-artifact-folder
       # create variable for identifying artifact folder
-      - echo "$(echo ${MULTI_CONF}${KAS_ARTIFACT_SUFFIX} | tr '[:lower:]' '[:upper:]' | tr '-' '_')=${KAS_ARTIFACT_FOLDER}" >> build.env
+      - echo "$(echo ${MULTI_CONF}${KAS_ARTIFACT_SUFFIX} | tr '-' '_')=${KAS_ARTIFACT_FOLDER}" >> build.env
 
   artifacts:
     kas-artifacts: # required vars: ARTIFACT_FOLDER
